-- MySQL Script generated by MySQL Workbench
-- Sun Jun 15 22:22:14 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema prados2dbv3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema prados2dbv3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `prados2dbv3` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `prados2dbv3` ;

-- -----------------------------------------------------
-- Table `prados2dbv3`.`Arrendatario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prados2dbv3`.`Arrendatario` (
  `idCedulaArrendatario` VARCHAR(12) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `celular` VARCHAR(45) NULL,
  `estado` TINYINT NULL,
  `numeroContrato` INT NULL,
  `responsable` TINYINT NULL,
  PRIMARY KEY (`idCedulaArrendatario`),
  UNIQUE INDEX `cedula_UNIQUE` (`idCedulaArrendatario` ASC) VISIBLE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `prados2dbv3`.`Parqueadero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prados2dbv3`.`Parqueadero` (
  `idParqueadero` VARCHAR(5) NOT NULL,
  `tipo_parqueadero` VARCHAR(45) NULL,
  `estado` TINYINT NULL,
  `observaciones` VARCHAR(45) NULL,
  PRIMARY KEY (`idParqueadero`),
  UNIQUE INDEX `id_parqueadero_UNIQUE` (`idParqueadero` ASC) VISIBLE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `prados2dbv3`.`Apartamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prados2dbv3`.`Apartamento` (
  `idApartamento` VARCHAR(10) NOT NULL,
  `tamañoApartamento` VARCHAR(45) NULL,
  `porcentaje` DECIMAL(5) NULL,
  PRIMARY KEY (`idApartamento`),
  UNIQUE INDEX `id_apartamento_UNIQUE` (`idApartamento` ASC) VISIBLE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `prados2dbv3`.`Propietario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prados2dbv3`.`Propietario` (
  `idCedulaPropietario` VARCHAR(12) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `celular` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `observaciones` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`idCedulaPropietario`),
  UNIQUE INDEX `id_cedula_propietario_UNIQUE` (`idCedulaPropietario` ASC) VISIBLE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `prados2dbv3`.`Funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prados2dbv3`.`Funcionarios` (
  `idCedula` VARCHAR(12) NOT NULL,
  `nombres` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `celular` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `rol` VARCHAR(45) NULL,
  UNIQUE INDEX `id_cedula_UNIQUE` (`idCedula` ASC) VISIBLE,
  PRIMARY KEY (`idCedula`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `prados2dbv3`.`SalonesSociales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prados2dbv3`.`SalonesSociales` (
  `idSalonesSocilales` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `tamaño` INT NULL,
  `sillas` INT NULL,
  `mesas` INT NULL,
  `valor` INT NULL,
  `observaciones` VARCHAR(45) NULL,
  `fechaEvento` VARCHAR(45) NULL,
  PRIMARY KEY (`idSalonesSocilales`),
  UNIQUE INDEX `idSalonesSocilales_UNIQUE` (`idSalonesSocilales` ASC) VISIBLE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `prados2dbv3`.`Trasteos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prados2dbv3`.`Trasteos` (
  `idTrasteos` INT NOT NULL AUTO_INCREMENT,
  `cedula` VARCHAR(45) NULL,
  `nombres` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `fechaTrasteo` DATE NULL,
  PRIMARY KEY (`idTrasteos`),
  UNIQUE INDEX `id_trasteos_UNIQUE` (`idTrasteos` ASC) VISIBLE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `prados2dbv3`.`Eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prados2dbv3`.`Eventos` (
  `idEvento` INT NOT NULL AUTO_INCREMENT,
  `nombreEvento` VARCHAR(45) NULL,
  `informacionEvento` VARCHAR(45) NULL,
  `fechaEvento` DATETIME NULL,
  `fechaPublicacionEvento` DATETIME NULL,
  PRIMARY KEY (`idEvento`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `prados2dbv3`.`Solicitudes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prados2dbv3`.`Solicitudes` (
  `idSolicitud` INT NOT NULL AUTO_INCREMENT,
  `fechaHoraInicioSolicitud` DATETIME NULL,
  `fechaRadicacion` VARCHAR(45) NULL,
  `fechaHoraFinSolicitud` DATETIME NULL,
  `tipoSolicitud` VARCHAR(45) NULL,
  PRIMARY KEY (`idSolicitud`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `prados2dbv3`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prados2dbv3`.`Usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `nombreUsuario` VARCHAR(45) NULL,
  `clave` VARCHAR(45) NULL,
  `fechaCreacion` DATETIME NULL,
  `correo` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuarios`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
